import java.net.URI
import java.util.Base64

plugins {
    id("com.android.application")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
}

// Phase 6.6 Gate 6 — cleartext HTTP is allowed for ONE host: the API the
// build was given. Flutter forwards every `--dart-define` to Gradle as
// `-Pdart-defines=<base64(KEY=VALUE)>,...`; the API_BASE_URL define is the
// single source of truth, so nothing here names an IP. An https base URL
// yields a config with no cleartext at all. Without the define the local
// default (the emulator's host alias, as in lib/core/config/env.dart) applies.
val dartDefines: Map<String, String> = (project.findProperty("dart-defines") as String?)
    ?.split(",")
    ?.filter { it.isNotBlank() }
    ?.mapNotNull { runCatching { String(Base64.getDecoder().decode(it), Charsets.UTF_8) }.getOrNull() }
    ?.mapNotNull { kv -> kv.indexOf('=').takeIf { it > 0 }?.let { kv.substring(0, it) to kv.substring(it + 1) } }
    ?.toMap()
    ?: emptyMap()
val apiBaseUrl: String = dartDefines["API_BASE_URL"] ?: "http://10.0.2.2:8080"
val apiUri = URI(apiBaseUrl)
val cleartextApiHost: String? = if (apiUri.scheme == "http" && !apiUri.host.isNullOrBlank()) apiUri.host else null

/** Writes `xml/network_security_config.xml` into a generated res root. */
abstract class GenerateNetworkSecurityConfig : DefaultTask() {
    @get:Input
    abstract val cleartextHost: Property<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val dir = outputDir.get().dir("xml").asFile
        dir.mkdirs()
        val host = cleartextHost.get()
        val domain = if (host.isBlank()) "" else """
    <!-- The alpha / local API host from API_BASE_URL. Nothing else may use http. -->
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="false">$host</domain>
    </domain-config>"""
        dir.resolve("network_security_config.xml").writeText(
            """<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by android/app/build.gradle.kts from the API_BASE_URL dart-define. Do not edit. -->
<network-security-config>
    <base-config cleartextTrafficPermitted="false" />$domain
</network-security-config>
""",
        )
    }
}

val generateNetworkSecurityConfig =
    tasks.register<GenerateNetworkSecurityConfig>("generateNetworkSecurityConfig") {
        description = "Allows cleartext only for the configured API host."
        cleartextHost.set(cleartextApiHost ?: "")
        outputDir.set(layout.buildDirectory.dir("generated/fitos/res"))
    }

androidComponents {
    onVariants { variant ->
        variant.sources.res?.addGeneratedSourceDirectory(
            generateNetworkSecurityConfig,
            GenerateNetworkSecurityConfig::outputDir,
        )
    }
}

android {
    namespace = "com.example.fitos"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        // flutter_local_notifications 19 needs core library desugaring for
        // the rest-timer notification (Phase 5, owner decision 8.4).
        isCoreLibraryDesugaringEnabled = true
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId = "com.example.fitos"
        // You can update the following values to match your application needs.
        // For more information, see: https://flutter.dev/to/review-gradle-config.
        // Phase 6.5: androidx.health.connect:connect-client:1.1.0 declares
        // minSdk 26 (Android 8.0); Flutter's default is 24. Health Connect
        // itself needs Android 9+, so nothing below 26 could use it anyway.
        minSdk = 26
        targetSdk = flutter.targetSdkVersion
        // Uses the version code from pubspec.yaml. When using split APKs, 1000 * ABI_VERSION
        // is added automatically by Flutter. (https://developer.android.com/studio/build/configure-apk-splits#configure-APK-versions)
        // You can force using the value of versionCode by specifying the `-P force-version-code-ignoring-abi=true`
        // flag during build.
        versionCode = flutter.versionCode
        versionName = flutter.versionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig = signingConfigs.getByName("debug")
        }
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

flutter {
    source = "../.."
}

dependencies {
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.4")
    // Phase 6.5 (owner D1): Health Connect read-only, through a thin in-app
    // channel — the stable client per developer.android.com (8 Oct 2025).
    implementation("androidx.health.connect:connect-client:1.1.0")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2")
}
